export const LabelActionTypes = {
    API_RESPONSE_SUCCESS: '@@label/API_RESPONSE_SUCCESS',
    API_RESPONSE_ERROR: '@@label/API_RESPONSE_ERROR',

    GET_ORDER: '@@label/GET_ORDER',
    GET_RATES_FOR_ORDER: '@@LABEL/GET_RATES_FOR_ORDER',
    CREATE_LABEL_FOR_ORDER: '@@label/CREATE_LABEL_FOR_ORDER',
    UPDATE_ORDER_AND_CREATE_LABEL: '@@label/UPDATE_ORDER_AND_CREATE_LABEL'
};
