export const AddressBookActionTypes = {
    API_RESPONSE_SUCCESS: '@@addresses/API_RESPONSE_SUCCESS',
    API_RESPONSE_ERROR: '@@addresses/API_RESPONSE_ERROR',
    READ_ALL_ADDRESSES_REQUEST: '@@addresses/READ_ALL_ADDRESSES_REQUEST',
    CREATE_ADDRESS_REQUEST: '@@addresses/CREATE_ADDRESS_REQUEST',
    READ_ADDRESS_REQUEST: '@@addresses/READ_ADDRESS_REQUEST',
    UPDATE_ADDRESS_REQUEST: '@@addresses/UPDATE_ADDRESS_REQUEST',
    DELETE_ADDRESS_REQUEST: '@@addresses/DELETE_ADDRESS_REQUEST'
};
